### ISSUE TITLE
Proposal: add the current time of the selected location

### ISSUE THREAD

**Issue by djavorszky** [alffox/around-the-world#2]
If I select an office, it would be nice to know their current time.

**Comment by alffox** [comment]
Hi @djavorszky , just a short update:

Backend changes were successfully implemented in pre-prod by taking advantage of http://worldclockapi.com/

When finished, the final result should also show the day of the week and the date, like e.g.:

```
🕒 02:59
📅 Friday, 2019-02-15
🌐 Pacific Standard Time
```

Next steps:

- Refine and test logic/render method and overall UX in pre-prod
- Implement in Prod

**Comment by alffox** [comment]
Hello @djavorszky , the feature is now live: https://liferay-aroundtheworld.wedeploy.io/, you may see it under the current location area in the navbar:

Would this be ok for you ? Do you have any other suggestions to make it better ?

**Comment by djavorszky** [comment]
Love it!

I'd make one change however: currently, when the page loads but the date/time is not yet fetched, that div is empty. This means that when it loads, there's a sudden jerk in the page where the div is populated and the date+time is shown - see gif:

![screen recording 2019-02-25 at 09 23 am](https://user-images.githubusercontent.com/1560451/53323688-228c6700-38df-11e9-9673-363817549ae9.gif)

Personally, I'd change this to always show the place with a placeholder-like message (e.g. "loading date and time"), and then update it to the correct values.

Also, seems like Netherlands doesn't work, and that the flag also gets pushed a bit to the right :)

**Comment by alffox** [comment]
Hello @djavorszky , thank you very much for the inputs, I corrected the error of showing no date and time for The Netherlands and refactored the render method for date and time, so that now there is an parent div with predefined styling, getting populated without altering the size:

![image](https://user-images.githubusercontent.com/30409634/53331635-ae0ef380-38f1-11e9-92d9-16ccc5a0455e.png)

If you would like to test all times on flags, please keep in mind that the timezone API has a limit of 1 call per second, shorter calls will be blocked.

Thanks again.

**Comment by djavorszky** [comment]
Looks great! Thanks for making the changes :-)
